addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.7")
addSbtPlugin("io.spray"                  % "sbt-revolver"   % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"       % "1.4.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-ghpages"    % "0.6.3")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"    % "0.6.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"     % "5.6.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.20")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"        % "0.4.3")
