addSbtPlugin("org.typelevel"             % "sbt-typelevel-ci-release" % "0.4.19")
addSbtPlugin("io.spray"                  % "sbt-revolver"             % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"                 % "1.4.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-ghpages"              % "0.6.3")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"              % "0.6.4")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"               % "5.9.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.4.2")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                  % "0.4.4")
addSbtPlugin("nl.zolotko.sbt"            % "sbt-jfr"                  % "0.0.1")

addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.10.1")
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.4.5")