addSbtPlugin("org.typelevel"             % "sbt-typelevel-ci-release" % "0.4.22")
addSbtPlugin("io.spray"                  % "sbt-revolver"             % "0.10.0")
addSbtPlugin("com.github.sbt"            % "sbt-site-paradox"         % "1.5.0")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"              % "0.6.4")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"               % "5.10.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.4.2")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                  % "0.4.5")
addSbtPlugin("nl.zolotko.sbt"            % "sbt-jfr"                  % "0.0.1")
