laika.title = Reference
laika.navigationOrder = [
  schema-sdl.md
  mapping-types.md
  query-algebra.md
  predicates.md
  filtering-paging-nodes.md
  cursor.md
  context-env.md
  result-problem.md
  elab-phases.md
  sql-mapping.md
  circe-mapping.md
  generic-derivation.md
  effects.md
  running-operations.md
]
